
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: ssh://localhost/config-repo
  security:
    user:
      name: root
      password: s3cr3t
